import dotenv from 'dotenv';
import mongoose from 'mongoose';
import User from '../models/User.js';
import ResidentProfile from '../models/ResidentProfile.js';
import ProviderProfile from '../models/ProviderProfile.js';
import Service from '../models/Service.js';
import CommunityPost from '../models/CommunityPost.js';

dotenv.config();

const seed = async () => {
  await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/trustbridge');
  console.log('Connected to MongoDB for seeding...');

  await mongoose.connection.dropDatabase();
  console.log('Database cleared');

  const admin = await User.create({
    name: 'Admin User',
    email: 'admin@trustbridge.com',
    password: 'admin123',
    role: 'admin',
    location: 'Hyderabad',
  });

  const newcomer = await User.create({
    name: 'Priya Sharma',
    email: 'priya@example.com',
    password: 'password123',
    role: 'newcomer',
    location: 'Bachupally',
    city: 'Hyderabad',
  });

  const residentUser = await User.create({
    name: 'Rajesh Kumar',
    email: 'rajesh@example.com',
    password: 'password123',
    role: 'resident',
    phone: '9876543210',
    phoneVerified: true,
    location: 'Miyapur',
    city: 'Hyderabad',
  });

  const residentProfile = await ResidentProfile.create({
    user: residentUser._id,
    trustScore: 85,
    yearsInArea: 8,
    verificationStatus: 'verified',
    verificationSteps: { phone: true, aadhaar: true, selfie: true, faceMatch: true, address: true },
    isVerifiedBadge: true,
    bio: 'Local resident helping newcomers settle in Miyapur area for 8 years.',
    languages: ['English', 'Hindi', 'Telugu'],
    specialties: ['Housing', 'Groceries', 'Transportation'],
    averageRating: 4.8,
    totalRatings: 24,
    helpfulInteractions: 56,
    communityPosts: 12,
    walletBalance: 2500,
    address: 'Miyapur, Hyderabad',
  });

  const providerUser = await User.create({
    name: 'Dr. Anil Reddy',
    email: 'anil@example.com',
    password: 'password123',
    role: 'provider',
    phone: '9123456789',
    location: 'Secunderabad',
    city: 'Hyderabad',
  });

  const providerProfile = await ProviderProfile.create({
    user: providerUser._id,
    businessName: 'Reddy Multi-Speciality Clinic',
    fullName: 'Dr. Anil Reddy',
    phone: '9123456789',
    address: 'Secunderabad, Hyderabad',
    gstNumber: '36AABCR1234A1Z5',
    verificationScore: 92,
    verificationStatus: 'verified',
    subscription: {
      plan: 'premium',
      status: 'active',
      startDate: new Date(),
      endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    },
    averageRating: 4.6,
    totalReviews: 18,
  });

  const services = [

    // ── RESTAURANTS ────────────────────────────────────────────────────────────
    {
      provider: providerUser._id,
      providerProfile: providerProfile._id,
      title: 'Virasat – The Exotic Veg',
      description: 'A premium vegetarian restaurant serving authentic Indian cuisines with a royal touch. Known for its rich Mughlai-style veg preparations, thalis, and desserts. Popular with families and working professionals.',
      category: 'Restaurants',
      location: 'Bachupally',
      address: 'Plot No. 12, Bachupally Main Road, Near Water Tank, Bachupally, Hyderabad – 500090',
      contactNumber: '040-23456781',
      price: 250,
      priceUnit: 'per person',
      images: ['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&h=400&fit=crop'],
      averageRating: 4.4,
      totalReviews: 38,
      totalBookings: 124,
      isVisible: true,
      isFeatured: true,
      isVerified: true,
      availability: {
        monday:    { open: '11:30', close: '22:30', closed: false },
        tuesday:   { open: '11:30', close: '22:30', closed: false },
        wednesday: { open: '11:30', close: '22:30', closed: false },
        thursday:  { open: '11:30', close: '22:30', closed: false },
        friday:    { open: '11:30', close: '23:00', closed: false },
        saturday:  { open: '11:30', close: '23:00', closed: false },
        sunday:    { open: '11:30', close: '22:30', closed: false },
      },
    },
    {
      provider: providerUser._id,
      providerProfile: providerProfile._id,
      title: 'Ujwala Grand Restaurant',
      description: 'Popular family restaurant in Bachupally serving delicious Andhra meals, biryanis, and North Indian dishes. Known for generous portions and great taste. A favourite among locals and newcomers alike.',
      category: 'Restaurants',
      location: 'Bachupally',
      address: 'Shop No. 12, JNTU Road, Bachupally, Hyderabad – 500090',
      contactNumber: '040-23456782',
      price: 200,
      priceUnit: 'per person',
      images: ['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&h=400&fit=crop'],
      averageRating: 4.4,
      totalReviews: 28,
      totalBookings: 98,
      isVisible: true,
      isFeatured: false,
      isVerified: true,
      availability: {
        monday:    { open: '07:00', close: '22:00', closed: false },
        tuesday:   { open: '07:00', close: '22:00', closed: false },
        wednesday: { open: '07:00', close: '22:00', closed: false },
        thursday:  { open: '07:00', close: '22:00', closed: false },
        friday:    { open: '07:00', close: '22:00', closed: false },
        saturday:  { open: '07:00', close: '22:30', closed: false },
        sunday:    { open: '08:00', close: '22:00', closed: false },
      },
    },
    {
      provider: providerUser._id,
      providerProfile: providerProfile._id,
      title: 'The Nosh Bistro',
      description: 'A modern café-style bistro in Bachupally offering continental breakfasts, sandwiches, pasta, and freshly brewed coffee. Perfect for students, remote workers, and casual dining. Free Wi-Fi available.',
      category: 'Restaurants',
      location: 'Bachupally',
      address: 'Ground Floor, Srinivasa Towers, Bachupally Ring Road, Bachupally, Hyderabad – 500090',
      contactNumber: '040-23456783',
      price: 300,
      priceUnit: 'per person',
      images: ['https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=600&h=400&fit=crop'],
      averageRating: 4.3,
      totalReviews: 21,
      totalBookings: 67,
      isVisible: true,
      isFeatured: false,
      isVerified: true,
      availability: {
        monday:    { open: '08:00', close: '22:00', closed: false },
        tuesday:   { open: '08:00', close: '22:00', closed: false },
        wednesday: { open: '08:00', close: '22:00', closed: false },
        thursday:  { open: '08:00', close: '22:00', closed: false },
        friday:    { open: '08:00', close: '22:30', closed: false },
        saturday:  { open: '08:30', close: '22:30', closed: false },
        sunday:    { open: '09:00', close: '21:00', closed: false },
      },
    },

    // ── HOSTELS / PGs ──────────────────────────────────────────────────────────
    {
      provider: providerUser._id,
      providerProfile: providerProfile._id,
      title: 'RamaDevi Boys Hostel',
      description: 'Affordable and well-maintained boys hostel near JNTU and VNR College, Bachupally. Offers single and double occupancy rooms with meals, Wi-Fi, RO water, and 24-hour security. Popular with college students and working professionals.',
      category: 'Hostels',
      location: 'Bachupally',
      address: 'Plot No. 7, Near JNTU Kukatpally, Bachupally Road, Hyderabad – 500090',
      contactNumber: '9849012345',
      price: 7500,
      priceUnit: 'per month',
      images: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=600&h=400&fit=crop'],
      averageRating: 4.2,
      totalReviews: 19,
      totalBookings: 45,
      isVisible: true,
      isFeatured: false,
      isVerified: true,
      recommendedBy: residentUser._id,
      availability: {
        monday:    { open: '06:00', close: '23:00', closed: false },
        tuesday:   { open: '06:00', close: '23:00', closed: false },
        wednesday: { open: '06:00', close: '23:00', closed: false },
        thursday:  { open: '06:00', close: '23:00', closed: false },
        friday:    { open: '06:00', close: '23:00', closed: false },
        saturday:  { open: '06:00', close: '23:00', closed: false },
        sunday:    { open: '06:00', close: '23:00', closed: false },
      },
    },
    {
      provider: providerUser._id,
      providerProfile: providerProfile._id,
      title: 'Sri Sai Manikanta Women\'s PG',
      description: 'A safe and comfortable women\'s PG accommodation in Bachupally with 24-hour security, CCTV surveillance, and a homely environment. Provides meals, Wi-Fi, attached bathrooms, and proximity to IT parks and colleges.',
      category: 'Hostels',
      location: 'Bachupally',
      address: 'H.No. 4-56, Near Bachupally Circle, Opposite SBI Bank, Bachupally, Hyderabad – 500090',
      contactNumber: '9848023456',
      price: 8000,
      priceUnit: 'per month',
      images: ['https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&h=400&fit=crop'],
      averageRating: 4.5,
      totalReviews: 31,
      totalBookings: 72,
      isVisible: true,
      isFeatured: true,
      isVerified: true,
      availability: {
        monday:    { open: '06:00', close: '22:00', closed: false },
        tuesday:   { open: '06:00', close: '22:00', closed: false },
        wednesday: { open: '06:00', close: '22:00', closed: false },
        thursday:  { open: '06:00', close: '22:00', closed: false },
        friday:    { open: '06:00', close: '22:00', closed: false },
        saturday:  { open: '06:00', close: '22:00', closed: false },
        sunday:    { open: '06:00', close: '22:00', closed: false },
      },
    },
    {
      provider: providerUser._id,
      providerProfile: providerProfile._id,
      title: 'Sri Vasavi Women\'s Hostel',
      description: 'A well-known women\'s hostel in Bachupally providing safe accommodation with round-the-clock security. Fully furnished rooms, hygienic meals, laundry facility, and close proximity to Bachupally IT corridor and VNR VJIET.',
      category: 'Hostels',
      location: 'Bachupally',
      address: 'Sri Vasavi Nagar, Chanda Nagar Road, Near Bachupally Water Tank, Hyderabad – 500090',
      contactNumber: '9000034567',
      price: 8500,
      priceUnit: 'per month',
      images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&h=400&fit=crop'],
      averageRating: 4.3,
      totalReviews: 24,
      totalBookings: 58,
      isVisible: true,
      isFeatured: false,
      isVerified: true,
      availability: {
        monday:    { open: '06:00', close: '22:30', closed: false },
        tuesday:   { open: '06:00', close: '22:30', closed: false },
        wednesday: { open: '06:00', close: '22:30', closed: false },
        thursday:  { open: '06:00', close: '22:30', closed: false },
        friday:    { open: '06:00', close: '22:30', closed: false },
        saturday:  { open: '06:00', close: '22:30', closed: false },
        sunday:    { open: '06:00', close: '22:30', closed: false },
      },
    },

    // ── GROCERY STORES ─────────────────────────────────────────────────────────
    {
      provider: providerUser._id,
      providerProfile: providerProfile._id,
      title: 'Seven To Ten Convenience Store',
      description: 'A well-stocked convenience store in Bachupally open extended hours for daily essentials, snacks, beverages, dairy products, and household items. Quick service and easy access for residents and newcomers.',
      category: 'Grocery Stores',
      location: 'Bachupally',
      address: 'Shop No. 3, Near Bachupally Bus Stop, Main Road, Bachupally, Hyderabad – 500090',
      contactNumber: '9701045678',
      price: 0,
      priceUnit: 'free',
      images: ['https://images.unsplash.com/photo-1542838132-92c53300491e?w=600&h=400&fit=crop'],
      averageRating: 4.1,
      totalReviews: 14,
      totalBookings: 33,
      isVisible: true,
      isFeatured: false,
      isVerified: true,
      availability: {
        monday:    { open: '07:00', close: '22:00', closed: false },
        tuesday:   { open: '07:00', close: '22:00', closed: false },
        wednesday: { open: '07:00', close: '22:00', closed: false },
        thursday:  { open: '07:00', close: '22:00', closed: false },
        friday:    { open: '07:00', close: '22:00', closed: false },
        saturday:  { open: '07:00', close: '22:00', closed: false },
        sunday:    { open: '08:00', close: '21:00', closed: false },
      },
    },
    {
      provider: providerUser._id,
      providerProfile: providerProfile._id,
      title: 'Vishal Mart',
      description: 'A large-format supermarket in Bachupally offering a wide range of fresh vegetables, fruits, packaged goods, household products, and daily essentials at competitive prices. Ample parking and home delivery available.',
      category: 'Grocery Stores',
      location: 'Bachupally',
      address: 'Plot No. 22, Bachupally Main Road, Near SBI ATM, Bachupally, Hyderabad – 500090',
      contactNumber: '040-27895600',
      price: 0,
      priceUnit: 'free',
      images: ['https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=600&h=400&fit=crop'],
      averageRating: 4.2,
      totalReviews: 22,
      totalBookings: 61,
      isVisible: true,
      isFeatured: false,
      isVerified: true,
      availability: {
        monday:    { open: '09:00', close: '21:30', closed: false },
        tuesday:   { open: '09:00', close: '21:30', closed: false },
        wednesday: { open: '09:00', close: '21:30', closed: false },
        thursday:  { open: '09:00', close: '21:30', closed: false },
        friday:    { open: '09:00', close: '21:30', closed: false },
        saturday:  { open: '09:00', close: '22:00', closed: false },
        sunday:    { open: '10:00', close: '21:00', closed: false },
      },
    },

    // ── PHARMACIES ─────────────────────────────────────────────────────────────
    {
      provider: providerUser._id,
      providerProfile: providerProfile._id,
      title: 'Sri Adithya Pharmacy',
      description: 'A trusted local pharmacy in Bachupally stocking a comprehensive range of prescription and OTC medicines, ayurvedic products, surgical supplies, and health supplements. Knowledgeable staff and quick home delivery.',
      category: 'Pharmacies',
      location: 'Bachupally',
      address: 'Shop No. 8, Bachupally Ring Road, Near Community Hall, Bachupally, Hyderabad – 500090',
      contactNumber: '9849056789',
      price: 0,
      priceUnit: 'free',
      images: ['https://images.unsplash.com/photo-1576602976047-174e57a47881?w=600&h=400&fit=crop'],
      averageRating: 4.4,
      totalReviews: 17,
      totalBookings: 41,
      isVisible: true,
      isFeatured: false,
      isVerified: true,
      availability: {
        monday:    { open: '08:00', close: '22:00', closed: false },
        tuesday:   { open: '08:00', close: '22:00', closed: false },
        wednesday: { open: '08:00', close: '22:00', closed: false },
        thursday:  { open: '08:00', close: '22:00', closed: false },
        friday:    { open: '08:00', close: '22:00', closed: false },
        saturday:  { open: '08:00', close: '22:00', closed: false },
        sunday:    { open: '09:00', close: '21:00', closed: false },
      },
    },
    {
      provider: providerUser._id,
      providerProfile: providerProfile._id,
      title: 'Apollo Pharmacy Bachupally',
      description: 'Apollo Pharmacy in Bachupally — part of India\'s largest pharmacy chain. Stocks all branded and generic medicines, personal care products, vitamins, and diagnostics kits. Offers prescription storage and home delivery.',
      category: 'Pharmacies',
      location: 'Bachupally',
      address: 'Apollo Hospital Complex, Bachupally Main Road, Hyderabad – 500090',
      contactNumber: '040-44886100',
      price: 0,
      priceUnit: 'free',
      images: ['https://images.unsplash.com/photo-1587854692152-c10426529373?w=600&h=400&fit=crop'],
      averageRating: 4.6,
      totalReviews: 29,
      totalBookings: 88,
      isVisible: true,
      isFeatured: true,
      isVerified: true,
      availability: {
        monday:    { open: '07:00', close: '23:00', closed: false },
        tuesday:   { open: '07:00', close: '23:00', closed: false },
        wednesday: { open: '07:00', close: '23:00', closed: false },
        thursday:  { open: '07:00', close: '23:00', closed: false },
        friday:    { open: '07:00', close: '23:00', closed: false },
        saturday:  { open: '07:00', close: '23:00', closed: false },
        sunday:    { open: '08:00', close: '22:00', closed: false },
      },
    },

    // ── CLINICS ────────────────────────────────────────────────────────────────
    {
      provider: providerUser._id,
      providerProfile: providerProfile._id,
      title: 'Edvenswa Holistic Healthcare',
      description: 'A modern holistic healthcare clinic in Bachupally offering general medicine, preventive care, nutrition counselling, and wellness therapies. Focuses on a whole-body approach to patient health. Experienced doctors and friendly staff.',
      category: 'Medical',
      location: 'Bachupally',
      address: 'H.No. 3-45/A, Road No. 2, Prashant Nagar, Bachupally, Hyderabad – 500090',
      contactNumber: '9000067890',
      price: 400,
      priceUnit: 'consultation',
      images: ['https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600&h=400&fit=crop'],
      averageRating: 4.5,
      totalReviews: 26,
      totalBookings: 79,
      isVisible: true,
      isFeatured: true,
      isVerified: true,
      availability: {
        monday:    { open: '09:00', close: '13:00', closed: false },
        tuesday:   { open: '09:00', close: '13:00', closed: false },
        wednesday: { open: '09:00', close: '13:00', closed: false },
        thursday:  { open: '09:00', close: '13:00', closed: false },
        friday:    { open: '09:00', close: '13:00', closed: false },
        saturday:  { open: '09:00', close: '13:00', closed: false },
        sunday:    { open: '10:00', close: '12:00', closed: false },
      },
    },
    {
      provider: providerUser._id,
      providerProfile: providerProfile._id,
      title: 'Little Tooth Stories',
      description: 'A friendly and child-focused dental clinic in Bachupally specialising in paediatric dentistry, orthodontics, and cosmetic dental treatments. Designed to make children comfortable and anxiety-free during dental visits.',
      category: 'Medical',
      location: 'Bachupally',
      address: 'Shop No. 5, Sri Sai Plaza, Near Railway Overbridge, Bachupally, Hyderabad – 500090',
      contactNumber: '9100078901',
      price: 500,
      priceUnit: 'consultation',
      images: ['https://images.unsplash.com/photo-1588776814546-1ffbb3b74e38?w=600&h=400&fit=crop'],
      averageRating: 4.7,
      totalReviews: 34,
      totalBookings: 102,
      isVisible: true,
      isFeatured: true,
      isVerified: true,
      availability: {
        monday:    { open: '10:00', close: '13:00', closed: false },
        tuesday:   { open: '10:00', close: '13:00', closed: false },
        wednesday: { open: '10:00', close: '13:00', closed: false },
        thursday:  { open: '10:00', close: '13:00', closed: false },
        friday:    { open: '10:00', close: '13:00', closed: false },
        saturday:  { open: '10:00', close: '14:00', closed: false },
        sunday:    { open: '00:00', close: '00:00', closed: true  },
      },
    },

  ];

  // Set all seed services as published and active
  await Service.insertMany(services.map(s => ({
    ...s,
    workflowStatus: 'published',
    isActive: true,
  })));

  await CommunityPost.create([
    {
      author: newcomer._id,
      title: 'Best hostel near VNR VJIET for boys?',
      content: 'I am joining VNR college next month. Looking for a clean and affordable boys hostel nearby in Bachupally. Any recommendations?',
      category: 'housing',
      location: 'Bachupally',
      tags: ['hostel', 'VNR', 'bachupally'],
      answers: [{
        author: residentUser._id,
        content: 'RamaDevi Boys Hostel near JNTU Bachupally Road is very popular among students. Clean rooms, good food, and 24-hour security. Sri Sai Manikanta PG is also good if you need more options.',
        upvotes: 7,
      }],
    },
    {
      author: newcomer._id,
      title: 'Where to find good grocery stores in Bachupally?',
      content: 'Just moved to Bachupally and looking for good grocery stores with fresh vegetables and home delivery.',
      category: 'general',
      location: 'Bachupally',
      tags: ['grocery', 'bachupally', 'fresh vegetables'],
      answers: [{
        author: residentUser._id,
        content: 'Vishal Mart on Bachupally Main Road is the best option — large selection and good prices. Seven To Ten Convenience Store near the bus stop is great for quick daily needs.',
        upvotes: 5,
      }],
    },
    {
      author: newcomer._id,
      title: 'Is there a good dental clinic in Bachupally?',
      content: 'Looking for a child-friendly dental clinic in Bachupally for my 7-year-old. Any recommendations?',
      category: 'healthcare',
      location: 'Bachupally',
      tags: ['dental', 'clinic', 'children', 'bachupally'],
      answers: [{
        author: residentUser._id,
        content: 'Little Tooth Stories near the Railway Overbridge in Bachupally is excellent for kids. The doctors are very patient with children and the clinic has a friendly atmosphere.',
        upvotes: 9,
      }],
    },
  ]);

  console.log('Seed data created successfully!');
  console.log('\nDemo Accounts:');
  console.log('  Admin:    admin@trustbridge.com / admin123');
  console.log('  Newcomer: priya@example.com / password123');
  console.log('  Resident: rajesh@example.com / password123');
  console.log('  Provider: anil@example.com / password123');

  await mongoose.disconnect();
};

seed().catch(console.error);
